import Head from 'next/head'
import Footer from '../components/Footer';
import Header from '../components/Header';
import CuriousMinds from '@/components/CuriousMinds';
import BookNow from '@/components/BookNow';
import Describe from '@/components/Describe';
import Gallery from '@/components/Gallery';
import Location from '@/components/Location';
import Reviews from '@/components/Reviews';


export default function Home() {
  return (
    <>
      <Head>
        <title>The Villa by Tamarind Shade - Your home away from home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/add/fav.ico" />
      </Head>
      <main>
        <Header />
        <Describe />
        <Gallery />
        <BookNow />
        <Reviews />
        <CuriousMinds />
        <Location />
        <Footer />
      </main>
    </>
  )
}
